### ISSUE TITLE
Change in related_field name can cause unnecessary migrations

### ISSUE THREAD

**Issue by amadornimbis** [chrisglass/django_polymorphic#135]
[This commit](https://github.com/chrisglass/django_polymorphic/commit/90933184e97e1ef2b1f45e6caa4b372fa4d2420c) added a single `+` character to the related name in migrations. This can cause the creation of an extra migration where the only difference between previous migrations (that were created with v0.6.1 of polymorphic) and future migrations (after you upgrade to v0.7). This is can be a bit problematic when, for example, if I am using the latest version of polymorphic to create all my new migrations when upgrading to Django 1.7, but when I go to install the latest version of [django-filer](https://github.com/stefanfoulis/django-filer), whose migrations were created with the a version of polymorphic before v0.7, Django prompts me to create a new migration for filer.

**Comment by vdboor** [comment]
Yes, that is sadly true. :-( The alternative was no working migrations because the related_name is obviously no valid Python variable name. I recommend those apps to update their migrations manually (e.g. insert that `+` character in the existing apps). We've added some Django 1.7/1.8 fixes in 0.7, so all apps are recommended to use that as base version.

**Comment by amadornimbis** [comment]
Thanks for the response!
