### ISSUE TITLE
BaseClass.objects.filter(foo='bar').delete() fails: IntegrityError: update on table myapp_parent. 123 is still referenced from table myapp_child

### ISSUE THREAD

**Issue by guettli** [chrisglass/django_polymorphic#143]
If I do `Parent.objects.filter(foo='bar').delete()` I get this exception.

How to delete several objects at once?

```
Error
Traceback (most recent call last):
  File "/home/foo_eins_d/src/foo-modarch/foo/tests/unit/utils/test_copy_archiv_config.py", line 20, in test_delete
    Parent.objects.filter(foo='bar').delete()
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/models/query.py", line 468, in delete
    collector.delete()
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/models/deletion.py", line 282, in delete
    sender=model, instance=obj, using=self.using
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/transaction.py", line 316, in __exit__
    connection.commit()
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/backends/__init__.py", line 171, in commit
    self._commit()
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/foo_eins_d/lib/python2.7/site-packages/django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
IntegrityError: update or delete on table "foo_parent" violates foreign key constraint "..." on table "foo_child"
DETAIL:  Key (id)=(1152) is still referenced from table "foo_child".
```

**Comment by guettli** [comment]
I solved it like this. This SQL works with PostgreSQL only:

```
alter table foo_child_model drop constraint  parent_model_ptr_id_refs_id_dbd009fb ; 
alter table foo_child_model add constraint parent_model_ptr_id_refs_id_dbd009fb
   FOREIGN KEY  (parent_model_ptr_id) REFERENCES parent_model(id) on delete cascade DEFERRABLE INITIALLY DEFERRED;
```
This way the delete on the parent table automatically cascades to the child tables.

This has the benefit that the DB does work much fast than Python :-)

**Comment by hottwaj** [comment]
Hi, I would not recommend the approach that you have just suggested.

The constraint on the Foreign Key and the "no cascade delete" option are there for a reason: to help prevent bad code damaging your data.

Imagine that there is a bug in django (or django-polymorphic) that causes the parent to be deleted but not the child - with the cascade delete option enabled this bug will end up deleting a load of your data.

From what I have observed Django generally takes the approach of managing all the deletes itself rather than letting the database do cascade deletes - this makes sure that if there is a bug or if Django or your models are not set up correctly then a database constraint will be broken and the delete will fail - hopefully preventing data loss as a result.

I've used django-polymorphic for a while and I'm sure it can correctly handle deletion of a parent, when models are set up correctly.  If you are having problems I would double check your Django models before changing "on cascade delete" constraints.

**Comment by guettli** [comment]
I read what you wrote:

{{{
Imagine that there is a bug in django (or django-polymorphic) that causes the parent to be deleted but not the child - with the cascade delete option enabled this bug will end up deleting a load of your data.
}}}

If there is a bug which deletes data which should not be deleted. Then .... That should not happen. And if it does we have backups.
I don't think a constraint could help in this case.

Yes Django does the delete on cascade dance itself. But AFAIK this is just to support databases which don't have this feature.

Back to the start:

Is it valid in django-polymorphic to to do this:

`Parent.objects.filter(foo='bar').delete()`

Maybe it is related to this issue: https://code.djangoproject.com/ticket/16128

Up to now we still use Django 1.6

**Comment by guettli** [comment]
Sorry for the noise. We had a typo in the data migration. The polymorphic ChildModel had a wrong ContentType attached.

Some things worked some not. It took as some time to find the root of the problem.

We had strange errors like:

queryset=MyPolymorphicModel.objects.filter(...)

assert queryset.count()==len(queryset)   # This failed ...

Again, sorry for the noise it is solved.
