### ISSUE TITLE
SystemCheckError when using Model and FK Field of same name

### ISSUE THREAD

**Issue by scottfisk** [chrisglass/django_polymorphic#195]
When I set up the following situation I am getting errors where I previously have not. It does not seem like `Base` should have a collision `sub`, but perhaps that is something new with how polymorphism is handled?
```python
class Base(PolymorphicModel):
    pass

class Sub(Base):
    pass

class SubB(Base):
    sub = models.ForeignKey(Sub, null=True, editable=False)
```

Yields a Django `SystemCheckError`
```
ERRORS:
pexp.SubB.sub: (models.E006) The field 'sub' clashes with the field 'sub' from model 'pexp.base'.
```

This broke during my upgrade to django-polymorphic 0.8.1 and Django 1.9.1.  This exact case worked with django-polymorphic 0.7.2 + Django 1.8

I fiddled around a bit but was unable to write a test that triggers this issue. I guess because it is part of the Django system checker. I also wasn't 100% sure if this was an issue with this library or django. I am still digging on that. 

EDIT: Looks like it works fine with 0.8.1 & Django 1.8.5 so it may be that django changed something with model inheritance.

**Comment by mbylstra** [comment]
Hi, we went through the same problem yesterday. Our fix was to change the field name, so we could continue to use Django 1.9. Another option was to disable the system check in settings.py but we decided against that, as it might mask other issues. My feeling is that this is an issue with Django Multi Table Inheritance in general, not particularly django-polymorphic. In your example, Django MTI will generate a field named `sub` on all instances of `Base`, which can be used to get to the child instance. In your example this automatically generated field clashes with your foreign key field which you've also named `sub`. See (https://docs.djangoproject.com/en/1.9/topics/db/models/#multi-table-inheritance)

I believe the issue is that there will be ambiguity. This may have worked in the past, but you may not have gotten back the instance you were expecting. I believe Django 1.9 must have a stricter check. So, the safest solution is to rename the FK field.

**Comment by scottfisk** [comment]
Thanks @mbylstra. After a couple more checks I found that if my base class was Abstract there was also no conflict. 

So:
```
class Base(PolymorphicModel):
    class Meta:
        abstract = true

class Sub(Base):
    pass

class SubB(Base):
    sub = models.ForeignKey(Sub, null=True, editable=False)
```
worked. So it is definitely a change to MTI in Django 1.9 as you found.

Unfortunately `Base` being abstract makes is unqueryable, which is something I need unable to be queried, which I need. Looks like I can try to take it up with Django and/or implement the fixed you identified.

**Comment by cowlicks** [comment]
I ran into this problem today. Would it be possible for django-polymorphic to add some special prefix, or suffix to its keys to avoid clashing with django's MTI?
